version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  app:
    build: .
    restart: always
    environment:
      CRAIGSLIST_DB_USER: root
      CRAIGSLIST_DB_PASSWORD: somepassword
      CRAIGSLIST_DB_HOST: db
      CRAIGSLIST_DB_DATABASE: test
      CRAIGSLIST_DB_TABLE: urls
      CRAIGSLIST_DB_FIELD_NAME: url
      CRAIGSLIST_TELEGRAM_BOT_TOKEN: ${CRAIGSLIST_TELEGRAM_BOT_TOKEN}
      CRAIGSLIST_TELEGRAM_CHANNEL: "@craigslistsfauto"
      CRAIGSLIST_START_TIME: "02:00PM"
      CRAIGSLIST_STOP_TIME: "07:00AM"
    command: go run main.go

volumes:
  db_data: {}

#  CREATE TABLE `urls` (
#  `url` varchar(300) NOT NULL,
#  PRIMARY KEY (`url`)
#  ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;